spring:
  application:
    name: config-server
  profiles:
    active:
    - native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/Ashutoshsk/SpringMicroservicesInAction.git
          searchPaths: GIT_REPOSITORY_FOR_CLOUD_CONFIG/config
server:
  port: 8071